// ==UserScript==
// @name          Darker userstyles.org
// @namespace     http://userstyles.org
// @description	  Darker userstyles.org uses dark colors, clean & easy on the eyes.
// @author        zigboom
// @homepage      https://userstyles.org/styles/133817
// @run-at        document-start
// @version       0.20191101065717
// ==/UserScript==
(function() {var css = "";
css += [
		"/* -=< Darker userstyles.org by Zigboom Designs >=- */",
		"",
		"",
		"@namespace url(http://www.w3.org/1999/xhtml);"
	].join("\n");
if (false || (document.domain == "userstyles.org" || document.domain.substring(document.domain.indexOf(".userstyles.org") + 1) == "userstyles.org"))
	css += [
		"html, body, #nav-view-responsive {",
		"    color:#aaaaaa !important;",
		"    background:#181818 !important;",
		"}",
		"",
		" * {",
		"    border-color:#444444 !important;",
		"     color: #aaa !important;",
		"}",
		"",
		"             ",
		"        ",
		" #main-header {",
		"    background:none !important;",
		"}",
		"",
		" a {",
		"    color:#cccccc !important;",
		"    text-decoration:none !important;",
		"    text-shadow:none;",
		"    transition:all .6s;",
		"}",
		"",
		" a:hover, h4 a:hover {",
		"    color:#eeeeee !important;",
		"    text-shadow:0 0 6px #ffffff !important;",
		"    transition:all .6s;",
		"}",
		" ",
		"a:visited, h4 a:visited {",
		"    color: #777 !important;",
		"}",
		"        ",
		" #left-sidebar > * {",
		"    background:none !important;",
		"}",
		"",
		".navigation .links-box .navigation-link, .navigation .links-box {",
		"    box-shadow: 0 -1px 0 0 #555, 0 0 0 0 #555;",
		"}",
		"",
		".navigation .links-box .navigation-link:hover, .us-stylecard--short, .rh, .us-stylecard--long {",
		"    background-color: #333 !important;",
		"}",
		"",
		"#top_android_button, .header-search .type_search, .personal-page .light-blue-button, .us-stylecard__button-container .us-button, .current, .div-arrow { ",
		"background: #444 !important;",
		"}",
		"",
		"#top_android_button:hover, .header-search .type_search:hover, .personal-page .light-blue-button:hover.us-stylecard__button-container .us-button:hover, .current:hover, .div-arrow:hover { ",
		"background: #555 !important;",
		"}",
		"",
		" #install {",
		"    background:none !important;",
		"    color:#aaaaaa !important;",
		"}",
		"",
		" .edit-style-option:nth-child(2n+1) {",
		"    background:none !important;",
		"}",
		"",
		" .ad {",
		"    display:none !important;",
		"}",
		"",
		"#overlay-info {",
		"    background-color: rgba(0, 0, 0, 0.98) !important;",
		"}",
		"",
		" #vanilla_discussions_index, pre, a.BigButton, #Head, .MessageForm, .Tabs, .Headings, .TabLink, .TabLink:link, ",
		" .TabLink:hover, .TabLink:active, .TabLink:visited, .Active .Tablink, .DataList .Meta a.Category, .Box,",
		"  .PanelInfo li, #vanilla_post_discussion, #DiscussionForm form,  .Activities .DataList li, .Foot, .Tabs .SubTab,",
		"   code, pre, .MessageList .Item, body.Discussion #Content, .DiscussionsTabs, .DataList .Item, #nav-view, #navigation  {",
		"    background:none !important;",
		"}",
		"        ",
		"         #header, .style_card, .see_more, .white_button, #css_button, #notes_textarea, #send_feedback_button, #archive_style_button, .navigation {",
		"            background: #282828 !important;",
		"        }",
		"        ",
		"        .navigation_link:hover, #create_new_style, #search_input, .see_more:hover, #search_input input, .white_button:hover, ",
		"        #css_button:hover, #send_feedback_button:hover, #archive_style_button:hover {",
		"            background: #333 !important;",
		"        }",
		"        ",
		"        .linksBox .navigation_link:last-child {",
		"    box-shadow: 0 1px 0 0 #000, 0 2px 0 0 #333 !important;",
		"}",
		"",
		"        .see_more, #search_input {",
		"            border: 1px solid;",
		"        }",
		"",
		" .Box dl dt, span.Title, h1, h2, h3, h4, h5, h6, .navigation_title, #copyrights, #bottomLinks  {",
		"    color:#aaaaaa !important;",
		"}",
		"",
		" #DiscussionForm label, .Activities li.Condensed .Excerpt, #create_new_style a, .footer_link a, .overrideHref a, h4 a, .author-name a, #as_userscript a {",
		"    color:#eeeeee !important;",
		"    text-decoration: none !important;",
		"}",
		"        ",
		"        #as_userscript a:hover, #install_style_button div {",
		"            color: #fff !important;",
		"             text-decoration: none !important;",
		"        }",
		"",
		" #vanilla_discussion_index, #dashboard_activity_index, #conversations_messages_all, #dashboard_profile_index,",
		"  #vanilla_categories_index, #footer {",
		"    background:none !important;",
		"    color:#eeeeee !important;",
		"}",
		"",
		" .Attachment:hover .FileHover {",
		"    background:#000000 !important;",
		"}",
		"",
		" #post-install-ad {",
		"    display:none !important;",
		"}",
		"",
		" INPUT:not([type=\"file\"]), TEXTAREA {",
		" -moz-appearance: none !important; ",
		" background-color: #282828 !important; ",
		" color: #aaaaaa !important; ",
		" border: 1px solid #444444 !important; ",
		" }",
		" ",
		" #search-submit, INPUT[type=\"file\"] {",
		" -moz-appearance: none !important; ",
		" background: linear-gradient(#333333, #181818) !important; ",
		" color: #aaaaaa !important; ",
		" border: 1px solid #444444 !important; ",
		" border-top-right-radius: 9px !important; ",
		" border-bottom-right-radius: 9px !important;  ",
		" }",
		" ",
		"  #search-submit:hover, INPUT[type=\"file\"]:hover {",
		" background: linear-gradient(#444444, #222222) !important;  ",
		" }",
		" ",
		" #search-submit {",
		"  float: left !important; ",
		"  }",
		" ",
		" #search-terms {",
		" -moz-appearance: none !important; ",
		" background: linear-gradient(#181818, #333333) !important; ",
		" color: #aaaaaa !important; ",
		" border-right: 0px solid #181818 !important; ",
		" border-top-left-radius: 9px !important; ",
		" border-bottom-left-radius: 9px !important; ",
		" padding-left: 4px !important; ",
		" width: 95px !important; ",
		" -moz-transition: all 1s !important; ",
		" margin-bottom: 12px !important; ",
		" }",
		" ",
		" #search-terms:focus {",
		"  width: 125px !important; ",
		"  -moz-transition: all 1s !important; ",
		"  }",
		"        ",
		".statistic table, th, td, #search_input input {",
		"    border: 0px !important;",
		"}",
		"",
		"",
		".author-styles {",
		"  border: 1px solid #333 !important;",
		"    border-collapse: collapse;",
		"}        ",
		"        ",
		".author-styles td {",
		"  border-top: 1px solid #444 !important;",
		"  padding: 4px 5px !important;",
		"}",
		"",
		".author-styles th {",
		"  padding: 4px 5px 4px !important;",
		"}",
		"        ",
		".numeric-value {",
		"    text-align: center !important;",
		"}",
		"        ",
		".logo {",
		"    filter: grayscale(1);",
		"    transition: all 0.6s;",
		"}",
		"   ",
		".logo:hover {",
		"    filter: grayscale(0);",
		"}",
		"        ",
		"  ",
		"/* --- */"
	].join("\n");
if (typeof GM_addStyle != "undefined") {
	GM_addStyle(css);
} else if (typeof PRO_addStyle != "undefined") {
	PRO_addStyle(css);
} else if (typeof addStyle != "undefined") {
	addStyle(css);
} else {
	var node = document.createElement("style");
	node.type = "text/css";
	node.appendChild(document.createTextNode(css));
	var heads = document.getElementsByTagName("head");
	if (heads.length > 0) {
		heads[0].appendChild(node);
	} else {
		// no head yet, stick it whereever
		document.documentElement.appendChild(node);
	}
}
})();
