#! /bin/sh

sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width             1
bspc config window_gap               4

bspc config split_ratio              0.55
bspc config borderless_monocle       true
bspc config paddingless_monocle false
bspc config gapless_monocle     false #Default setup uses negative padding, and gapless monocle looks really weird like that
bspc config single_monocle           true

bspc config pointer_follows_focus    false

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc config external_rules_command "$HOME/.config/bspwm/external_rules.sh"
