#! /bin/sh
sxhkd &

gap=5
PANEL_HEIGHT=0
export gap
export PANEL_HEIGHT

#This creates negative padding equal to window gap so that gaps are shown only between windows and not on desktop edges.
bspc config window_gap $gap
bspc config top_padding $(($PANEL_HEIGHT-$gap))
bspc config left_padding -$gap
bspc config right_padding -$gap
bspc config bottom_padding -$gap

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width             1
bspc config window_gap               4
bspc config split_ratio              0.55
bspc config borderless_monocle       true
bspc config paddingless_monocle false
bspc config gapless_monocle     false #Default setup uses negative padding, and gapless monocle looks really weird like that
bspc config single_monocle           true

bspc config pointer_follows_focus    false

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a spotify state=pseudo_tiled
bspc rule -a firefox private=on
bspc config external_rules_command "$HOME/.config/bspwm/external_rules.sh"
